server:
  servlet:
    context-path: "/publisher"
  error:
    whitelabel:
      enabled: true

spring:
  application:
    name: "Publisher"
  datasource:
    url: "jdbc:postgresql://localhost:5432/publisher"
    username: "postgres"
    password: "gt65hash87qq"
  jpa:
    hibernate:
      ddl-auto: "validate"
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
